ignore:
  #No es codigo nuestro
  - "gatling-charts-highcharts-bundle-3.3.1"
  - "node-solid-server"
  - "src/leaflet-files"
  #No deberia ser comprobado asi
  - "src/BackEnd"
  - "src/docs"
  #Por completar, siguiendo el modelo BlackList, los comprobados ya no estan en la lista
  - "src/front-end/model"
  - "src/front-end/layouts"
  #De components
  #Del mapa
  - "src/front-end/components/map/MapPointModal.jsx"
  - "src/front-end/components/map/MapRuta.jsx"
  - "src/front-end/components/map/AddRouteMap.jsx"
  #Opciones para compartir
  - "src/front-end/components/share/PhotoGallery.jsx"
  - "src/front-end/components/share/ShareView.jsx"
  - "src/front-end/components/share/CommentBox.jsx"
  #NavBAr
  - "src/front-end/components/AuthNavBar/auth-nav-bar.component.jsx"
  #Relacionado con amigos
  - "src/front-end/components/friends/AddFriend.jsx"
  - "src/front-end/components/friends/Friends.jsx"
  #Innecesario
  - "src/index"
  - "src/serviceWorker"
  - "src/jest-puppeteer.config.js"