ignore:
  #No es codigo nuestro
  - "gatling-charts-highcharts-bundle-3.3.1"
  - "node-solid-server"
  - "src/leaflet-files"
  #No deberia ser comprobado asi
  - "src/BackEnd"
  - "src/docs"
  #Del mapa
  - "src/front-end/components/map/MapPointModal.jsx"
  - "src/front-end/components/map/MapRuta.jsx"
  - "src/front-end/components/map/AddRouteMap.jsx"
  #Por completar, siguiendo el modelo BlackList, los comprobados ya no estan en la lista
  #De generalidades
  - "src/front-end/model/Comentario.js"
  - "src/front-end/model/Notificacion.js"
  #De components
  #Opciones para compartir
  #- "src/front-end/components/share/PhotoGallery.jsx"
  - "src/front-end/components/share/ShareView.jsx"
  #Relacionado con amigos
  #- "src/front-end/components/friends/AddFriend.jsx"
  #- "src/front-end/components/friends/Friends.jsx"
  #Innecesario comprobarlo 
  - "src/index"
  - "src/serviceWorker"
  - "src/jest-puppeteer.config.js"
