ignore:
  - "src/leaflet-files" #Definitivo
  #No es codigo nuestro
  - "gatling-charts-highcharts-bundle-3.3.1"
  - "node-solid-server"
  #No deberia ser comprobado asi
  - "src/BackEnd"
  - "src/docs"
   #Por completar
  - "src/front-end/model"
  - "src/serviceWorker"
  - "App"
  - "src/front-end/layouts"
  - "/src/front-end/components/map/MapPointModal"
  - "/src/front-end/components/map/MapRuta/"
  - "/src/front-end/components/map/AddRouteMap/"