version: '3.4'

services:
  viade_es5b:
    image: viade_es5b
    build: .
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
  solidserver:
    image: nodesolidserver/node-solid-server
    build: ./node-solid-server/
    volumes:
      - ./volumes/soliddata:/usr/src/app/data
      - ./volumes/soliddb:/usr/src/app/.db
    ports:
      - "8443:8443"
volumes:
  soliddata:
    external: false
  soliddb:
    external: false